#!/usr/bin/env python
"""Run relately from the current dir."""
import os
import argparse

from relately.server import get_instance

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Query access via REST to PostgreSQL database.',
    )
    parser.add_argument('--no-debug','-N',
        dest='debug',
        action='store_false',
        help="don't show debugger on exception or reload on file update",
    )
    parser.add_argument('--port','-p',
        dest='port',
        nargs='?',
        type=int,
        help='port to serve from',
        default=8000
    )

    parser.add_argument('--dbname','-d',
        dest='dbname',
        nargs='?',
        type=str,
        help='name of postgresql database to connect to',
        default='relately'
    )

    parser.add_argument('--user','-u',
        dest='username',
        nargs='?',
        type=str,
        help='name of postgresql user to connect with',
        default='relately'
    )

    parser.add_argument('--password',
        dest='password',
        nargs='?',
        type=str,
        help='password for postgresql user',
        default='relately'
    )

    args = parser.parse_args()
    app = get_instance(
        dbname=args.dbname,
        username=args.username,
        password=args.password
    )
    app.config['DEBUG'] = args.debug
    app.run(port=args.port)